<?php

namespace pizzashop\tests\order;

use Faker\Factory;
use PHPUnit\Framework\Attributes\DataProvider;
use pizzashop\shop\domain\entities\order\Order;
use pizzashop\shop\domain\entities\order\Item;
use Illuminate\Database\Capsule\Manager as DB;
use pizzashop\shop\domain\service\catalogue\ServiceCatalogue;
use pizzashop\shop\domain\service\classes\CatalogService;
use pizzashop\shop\domain\service\commande\ServiceCommande;

class ServiceCommandeTest extends \PHPUnit\Framework\TestCase {

    private static $orderIds = [];
    private static $itemIds = [];
    private static $productService;
    private static $orderService;
    private static $faker;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();
        $dbcom = __DIR__ . '/../../config/commande.db.test.ini';
        $dbcat = __DIR__ . '/../../config/catalog.db.ini';
        $db = new DB();
        $db->addConnection(parse_ini_file($dbcom), 'commande');
        $db->addConnection(parse_ini_file($dbcat), 'catalog');
        $db->setAsGlobal();
        $db->bootEloquent();

        self::$productService = new CatalogService();
        self::$orderService = new OrderService(self::$productService);
        self::$faker = Factory::create('fr_FR');
        self::fill();

    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        self::cleanDB();
    }


    private static function cleanDB(){
        foreach (self::$orderIds as $id){
            Order::find($id)->delete();
        }
        foreach (self::$itemIds as $id){
            Item::find($id)->delete();
        }
    }
    private static function fill() {

   	 	// TODO : créer une commande dans la base pour tester l'accès à une commande
    }


    public function testAccederCommande(){
        //$id = self::$commandeIds[0];
        foreach (self::$orderIds as $id){
            $orderEntity = Order::find($id);
            $orderDTO = self::$orderService->getOrder($id);
            $this->assertNotNull($orderDTO);
 
            // TODO : comparer les données de l'entité et du DTO
        }


    }

}