version: '3'
networks:
  pizza-shop.net:
    driver: bridge
services:

  # service api.pizza-shop : api pour la prise de commandes
  #
  api.pizza-shop:
    image: 'canals/php:8.2'
    env_file: ./shop.env
    ports:
      - '2080:80' #40501
      - '1443:443' #40502
    volumes:
      - ../shop.pizza-shop/public:/var/www/html
      - ../shop.pizza-shop:/var/www
    working_dir: /var/www/
    networks:
      pizza-shop.net:
        aliases:
          - api.pizza-shop.local
    depends_on:
      - pizza-shop.commande.db
      - pizza-shop.catalogue.db



  # service sql pour le stockage des commandes -
  # utilisé par l'api order
  pizza-shop.commande.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./shop.env
    ports:
      - '3307:3306' # 40503
    networks:
      - pizza-shop.net
    volumes:
      - ../shop.pizza-shop/sql:/var/sql
      - ../shop.pizza-shop/sql/order:/docker-entrypoint-initdb.d


  # service sql pour le catalogue des pizzas -
  # utilisé par l'api order
  pizza-shop.catalogue.db:
    image: 'postgres:latest'
    env_file: ./cat.env
    ports:
      - '3308:5432' # 40504
    networks:
      - pizza-shop.net
    volumes:
      - ../shop.pizza-shop/sql:/var/sql'
      - ../shop.pizza-shop/sql/catalog:/docker-entrypoint-initdb.d
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '8081:8080' ## 40510
    networks:
      - pizza-shop.net

  ######################################
  ###  AUTH Service : service d'authentification JWT
  ###  api api.auth : auth, check, refresh de token JWT
  ###  utilise sa propre base de données
  ######################################
  api.pizza-auth:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '2082:80' ## 40506
      - '1444:443' ## 40507
    volumes:
      - ../auth.pizza-shop/public:/var/www/html
      - ../auth.pizza-shop:/var/www
    working_dir: /var/www
    networks:
      pizza-shop.net:
        aliases:
          - auth.pizza-shop.local
    depends_on:
      - pizza-shop.auth.db
    command: >
      bash -c "composer install && composer update && apache2-foreground"


  pizza-shop.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '3309:3306' ## 40508
    networks:
      - pizza-shop.net
    volumes:
      - ../auth.pizza-shop/sql:/var/sql
      - ../auth.pizza-shop/sql:/docker-entrypoint-initdb.d

  gateway.pizza-shop:
      image: 'canals/php:8.2'
      env_file: ./gate.env
      ports:
        - '2081:80'  # 40505
        - '1445:443' # 40510
      volumes:
        - ../gateway.pizza-shop:/var/www
        - ../gateway.pizza-shop/public:/var/www/html
      working_dir: /var/www/
      networks:
        pizza-shop.net:
          aliases:
            - api.pizza-shop.local
      depends_on:
        - api.pizza-shop
        - api.pizza-auth
      command: >
        bash -c "composer install && composer update && apache2-foreground"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - pizza-shop.net
    volumes:
      - ./rabbitmq_dir:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=@admin1#!

  pizza-shop.prod.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./prod.env
    networks:
      - pizza-shop.net
    volumes:
      - ../prod.pizza-shop/sql:/var/sql
      - ../prod.pizza-shop/sql:/docker-entrypoint-initdb.d



  api.prod.pizza-shop:
    image: node:alpine
    networks:
      - pizza-shop.net
    working_dir: /usr/app
    command: sh -c "npm i && npm run dev" #for development only
    #command: sh -c "npm i && npm start" #for production only
    volumes:
      - ../prod.pizza-shop:/usr/app
    ports:
      - '3333:3000'
    env_file:
      - prod.env
    depends_on:
      - pizza-shop.prod.db

